//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.14 at 12:46:59 AM ADT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://map.osm.me/osm-doc-part", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package me.osm.osmdoc.model.v2;
